# Generated by Django 6.0.5 on 2026-05-19 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_type', models.CharField(choices=[('prepaid', 'Prepaid'), ('postpaid', 'Postpaid')], default='prepaid', max_length=10)),
                ('meter_number', models.CharField(max_length=50, unique=True)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('debt', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('address', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
    ]
