# Generated by Django 6.0.5 on 2026-05-27 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostpaidContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('activation_method', models.CharField(choices=[('inspection', 'Solicitar Vistoria'), ('system_suggestion', 'Sugestão do Sistema')], max_length=30)),
                ('status', models.CharField(choices=[('pending_inspection', 'Aguardando Vistoria'), ('pending_approval', 'Aguardando Aprovação'), ('active', 'Activo'), ('rejected', 'Rejeitado')], db_index=True, default='pending_inspection', max_length=30)),
                ('appliances', models.JSONField(blank=True, default=list)),
                ('is_commercial', models.BooleanField(default=False)),
                ('inspection_notes', models.TextField(blank=True, default='')),
                ('admin_approval_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='postpaid_contract', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Postpaid Contract',
                'verbose_name_plural': 'Postpaid Contracts',
            },
        ),
    ]
